FROM confluentinc/cp-kafka-connect:7.5.1

RUN confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:15.0.0

# Opcional: Definir o plugin path por padrão para facilitar a configuração
# ENV CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components,/etc/kafka-connect/jars/elasticsearch"
