services:
  api:
    build:
      context: ./src/SampleLogs.PrometheusGrafana
      dockerfile: Dockerfile
      args:
        version: 1
    image: sample-logs-prometheus-grafana
    ports:
      - 8080:8080
    networks:
      - web_api_metrics_network
  prometheus:
    build:
      context: ./prometheus-grafana/prometheus
      dockerfile: Dockerfile
      args:
        version: 1
    image: prometheus-local
    restart: always
    ports:
      - 9090:9090
    networks:
      - web_api_metrics_network
    volumes:
      - './prometheus-grafana/prometheus/data:/data'

networks:
  web_api_metrics_network:
    #driver: overlay
    driver: bridge