services:
  api:
    build:
      context: ./src/SampleLogs.PrometheusGrafana
      dockerfile: Dockerfile
      args:
        version: 1
    image: sample-logs-prometheus-grafana
    ports:
      - 8080:8080
    networks:
      - web_api_metrics_network

  prometheus:
    build:
      context: ./prometheus-grafana/prometheus
      dockerfile: Dockerfile
      args:
        version: 1
    image: prometheus-local
    restart: always
    ports:
      - 9090:9090
    networks:
      - web_api_metrics_network
    volumes:
      - "./prometheus-grafana/prometheus/data:/data"

  grafana:
    build:
      context: ./prometheus-grafana/grafana
      dockerfile: Dockerfile
      args:
        version: 1
    image: grafana-local
    restart: always
    ports:
      - 3000:3000
    networks:
      - web_api_metrics_network

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./prometheus-grafana/loki/loki-config.yml:/etc/loki/local-config.yaml
      - ./data/loki:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - web_api_metrics_network

networks:
  web_api_metrics_network:
    #driver: overlay
    driver: bridge
