# config file version
apiVersion: 1

datasources:
  - name: prometheus-metrics
    editable: true
    type: prometheus
    access: proxy
    url: http://prometheus:9090/
    isDefault: true
  - name: loki-logs
    editable: true
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      timeout: 60
      maxLines: 1000
