global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "web-api-metrics-job"
    static_configs:
      - targets: ["api:8080"]
    metrics_path: /metrics
    params:
      accept: [application/openmetrics-text]